### ISSUE TITLE
dynamodb: exception when secondary indexes have same value

### ISSUE THREAD

**Issue by zakgof** [zakgof/velvetdb#2]
`Caused by: java.lang.IllegalStateException: Duplicate key com.zakgof.db.velvet.dynamodb.DynamoDBVelvet$Store$StoreIndex@611dba71
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.zakgof.db.velvet.dynamodb.DynamoDBVelvet$Store.<init>(DynamoDBVelvet.java:411)
	at com.zakgof.db.velvet.dynamodb.DynamoDBVelvet$SortedStore.<init>(DynamoDBVelvet.java:634)
	at com.zakgof.db.velvet.dynamodb.DynamoDBVelvet.sortedStoreWithProxy(DynamoDBVelvet.java:342)
	at com.zakgof.db.velvet.impl.cache.CachingVelvet$CachedSortedStore.<init>(CachingVelvet.java:154)
	at com.zakgof.db.velvet.impl.cache.CachingVelvet.sortedStore(CachingVelvet.java:40)
	at com.zakgof.db.velvet.impl.entity.SortedEntityDef.store(SortedEntityDef.java:23)
	at com.zakgof.db.velvet.impl.entity.SortedEntityDef.store(SortedEntityDef.java:15)
	at com.zakgof.db.velvet.impl.entity.EntityDef.queryKeys(EntityDef.java:174)
	at com.zakgof.db.velvet.impl.entity.EntityDef.queryList(EntityDef.java:162)`

**Comment by zakgof** [comment]
Not confirmed
